### ISSUE TITLE
Комментарии

### ISSUE THREAD

**Issue by ubcent** [AxAmat/js-repo#1]
Добрый день. 
1. [L50](https://github.com/AxAmat/js-repo/blob/master/jquery.html#L50) selected это не атрибут, а свойство. Об отличиях почитать можно [здесь](http://api.jquery.com/prop/). Соответственно и метод лучше использовать другой. 
2. [L46](https://github.com/AxAmat/js-repo/blob/master/jquery.html#L46) попробуйте сделать то же самое с помощью цикла [$.each](https://github.com/AxAmat/js-repo/blob/master/jquery.html#L46)
3. Добавьте readme.md в репо

**Comment by AxAmat** [comment]
Готово! :)
