### ISSUE TITLE
Проблемы с увеличением количества вкладок

### ISSUE THREAD

**Issue by ubcent** [AxAmat/js-repo#2]
Добрый день, Алексей. Ваш вариант реализации неплох, но на мой взгляд имеет существенный недостаток. А именно, при увеличении количества вкладок придется переписывать код. Подумайте как можно решить эту проблему.

**Comment by AxAmat** [comment]
День добрый, Дмитрий!
Спасибо, буду исправлять этот недостаток. И оформление заодно подправлю.
Утром GeekBrains был недоступен. Делал ДЗ по памяти из вчерашнего урока.

**Comment by AxAmat** [comment]
Дмитрий, переделал решение: получилась функция всего в 3 строчки!
Посмотрите, пожалуйста, на правильном ли я пути?

**Comment by ubcent** [comment]
Да, так намного лучше.
