### ISSUE TITLE
Дополнительное задание

### ISSUE THREAD

**Issue by ubcent** [AxAmat/js-repo#3]
[L6](https://github.com/AxAmat/js-repo/blob/master/form-validation/script.js#L6) попробуйте для сбора данных с формы воспользоваться методами [serialize](https://api.jquery.com/serialize/) и [serializeArray](https://api.jquery.com/serializeArray/)

**Comment by AxAmat** [comment]
Почему-то с применением методов serializeArray() и .serialize() возвращается "false". Хотя все данные из полей отправляются в надлежащем виде. Отправляю через load() и через ajax().
Может невнимательность где-то проявил?
